export const skin = defineSkin({
    sprites: {
        key: 'Wordle Key',
        blank: 'Wordle Blank',
        grey: 'Wordle Grey',
        yellow: 'Wordle Yellow',
        green: 'Wordle Green',

        enter: 'Wordle Enter',
        backspace: 'Wordle Backspace',

        letterA: 'Wordle Letter A',
        letterB: 'Wordle Letter B',
        letterC: 'Wordle Letter C',
        letterD: 'Wordle Letter D',
        letterE: 'Wordle Letter E',
        letterF: 'Wordle Letter F',
        letterG: 'Wordle Letter G',
        letterH: 'Wordle Letter H',
        letterI: 'Wordle Letter I',
        letterJ: 'Wordle Letter J',
        letterK: 'Wordle Letter K',
        letterL: 'Wordle Letter L',
        letterM: 'Wordle Letter M',
        letterN: 'Wordle Letter N',
        letterO: 'Wordle Letter O',
        letterP: 'Wordle Letter P',
        letterQ: 'Wordle Letter Q',
        letterR: 'Wordle Letter R',
        letterS: 'Wordle Letter S',
        letterT: 'Wordle Letter T',
        letterU: 'Wordle Letter U',
        letterV: 'Wordle Letter V',
        letterW: 'Wordle Letter W',
        letterX: 'Wordle Letter X',
        letterY: 'Wordle Letter Y',
        letterZ: 'Wordle Letter Z',
    },
})
